pipeline:
  name: TestPipeline
  identifier: TestPipeline
  projectIdentifier: Test
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1692859495866
        repoName: Harness-Pipeline
        build: <+input>
  stages:
    - stage:
        name: MyTest
        identifier: MyTest
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: "pipeline:\r\n  name: test project\r\n  identifier: test_project\r\n  projectIdentifier: default_project\r\n  orgIdentifier: default\r\n  tags: {}\r\n\r\nResources:\r\n  MyVPC:\r\n    Type: AWS::EC2::VPC\r\n    Properties:\r\n      CidrBlock: 10.0.0.0/16\r\n\r\n  PublicSubnetA:\r\n    Type: AWS::EC2::Subnet\r\n    Properties:\r\n      VpcId: vpc-0326e947481bfb18d\r\n      CidrBlock: 10.0.0.0/26\r\n      AvailabilityZone: ap-southeast-1\r\n\r\n  PublicSubnetB:\r\n    Type: AWS::EC2::Subnet\r\n    Properties:\r\n      VpcId: vpc-0326e947481bfb18d\r\n      CidrBlock: 10.0.0.64/26\r\n      AvailabilityZone: ap-southeast-1\r\n\r\n  PrivateSubnetA:\r\n    Type: AWS::EC2::Subnet\r\n    Properties:\r\n      VpcId: vpc-0326e947481bfb18d\r\n      CidrBlock: 10.0.0.128/26\r\n      AvailabilityZone: ap-southeast-1\r\n\r\n  PrivateSubnetB:\r\n    Type: AWS::EC2::Subnet\r\n    Properties:\r\n      VpcId: vpc-0326e947481bfb18d\r\n      CidrBlock: 10.0.0.192/26\r\n      AvailabilityZone: ap-southeast-1\r\n"
